<!-- Generated by ::xowiki::ADP_Generator on Mon Sep 19 20:32:06 BRT 2011 -->
<!-- The following DIV is needed for overlib to function! -->
  <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>	
<div class='xowiki-content'>

@top_includelets;noquote@
<h1>@title@</h1>
@content;noquote@

</div> <!-- class='xowiki-content' -->
